import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/* ✅ HEADER global (todas las páginas) */
import SiteHeader from "@/components/layout/SiteHeader";

/* ✅ FOOTER global (todas las páginas) */
import SiteFooter from "@/components/layout/SiteFooter";

/* ✅ ULUBIONE (wishlist) — Provider + Modal global */
import UlubioneProvider from "@/components/ulubione/UlubioneProvider";
import UlubioneModal from "@/components/ulubione/UlubioneModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl" suppressHydrationWarning>
      <body
        className={[
          geistSans.variable,
          geistMono.variable,
          "antialiased",
          // ✅ THEME GLOBAL (blanco / negro + dorado)
          "min-h-screen bg-white text-black",
        ].join(" ")}
      >
        {/* ✅ Provider global para que el corazón funcione en TODA la app */}
        <UlubioneProvider>
          {/* ✅ Layout global: Header + Page + Footer */}
          <div className="min-h-screen flex flex-col">
            <SiteHeader />

            {/* ✅ Contenido de cada página */}
            <div className="flex-1">{children}</div>

            {/* ✅ Footer global (ancho completo) */}
            <SiteFooter />
          </div>

          {/* ✅ Modal global (se abre al agregar a Ulubione) */}
          <UlubioneModal />
        </UlubioneProvider>
      </body>
    </html>
  );
}
